# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 80, 1131, 571))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 204);\n"
"border-style: groove;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(60, 50, 1011, 461))
        self.widget.setStyleSheet("border: 1px solid black;")
        self.widget.setObjectName("widget")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setGeometry(QtCore.QRect(10, 160, 611, 291))
        self.tableView.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 61, 21))
        self.label_5.setStyleSheet("border : 0px;")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 10, 191, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border : 1px solid black;")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(720, 240, 191, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border : 1px solid black;")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(630, 240, 61, 21))
        self.label_4.setStyleSheet("border : 0px;")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(650, 270, 31, 21))
        self.label_8.setStyleSheet("border : 0px;")
        self.label_8.setObjectName("label_8")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setGeometry(QtCore.QRect(870, 410, 131, 41))
        self.lcdNumber.setStyleSheet("border : 0px;\n"
"color: rgb(85, 255, 0);\n"
"background-color: rgb(29, 29, 29);")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Bin)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(720, 270, 191, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border : 1px solid black;")
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(780, 410, 81, 41))
        self.label.setStyleSheet("font: 10 10pt \"MS Shell Dlg 2\";\n"
"border : 0px;")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 420, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b9ffb9;       /* darker when pressed */\n"
"    border-style: inset;             /* gives a pushed-in look */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/delete-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(640, 300, 61, 21))
        self.label_11.setStyleSheet("border : 0px;")
        self.label_11.setObjectName("label_11")
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setGeometry(QtCore.QRect(720, 300, 191, 22))
        self.spinBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setAccelerated(False)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setSuffix("")
        self.spinBox.setPrefix("")
        self.spinBox.setMaximum(100)
        self.spinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(710, 360, 75, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b9ffb9;       /* darker when pressed */\n"
"    border-style: inset;             /* gives a pushed-in look */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/blue-save-disk-icon-0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(630, 330, 71, 21))
        self.label_12.setStyleSheet("border : 0px;")
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(720, 330, 191, 21))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border : 1px solid black;")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setPlaceholderText("")
        self.lineEdit_7.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_7.setClearButtonEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 360, 121, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bdfff8;       /* darker when pressed */\n"
"    border-style: inset;             /* gives a pushed-in look */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 611, 111))
        self.plainTextEdit.setStyleSheet("font: 11pt \"Courier New\";")
        self.plainTextEdit.setDocumentTitle("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setPlaceholderText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(660, 10, 311, 221))
        self.label_2.setStyleSheet("border : 0pt;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/Logo MB 02 (1).PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 390, 75, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b9ffb9;       /* darker when pressed */\n"
"    border-style: inset;             /* gives a pushed-in look */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "    Order No :"))
        self.label_4.setText(_translate("MainWindow", "     Search :"))
        self.label_8.setText(_translate("MainWindow", "Paid :"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Only int value"))
        self.label.setText(_translate("MainWindow", "Grand Total :"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.label_11.setText(_translate("MainWindow", "Discount % :"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.label_12.setText(_translate("MainWindow", "    Cash Back :"))
        self.pushButton_3.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
