# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menu_master_input import menu_class
from menu_item import menu_item_class
from type_of_item import item_category_class
from main_menu_item import main_menu_of_item_class
from new_order import new_order_class
from order_bill import customer_order_bill
from order_status import punch_order_status


class home_screen(object):
    def setupUi(self, MainWindow, username, usertype, userid):
        self.username = username
        self.usertype = usertype
        self.userid = userid
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 80, 1131, 571))
        self.label.setStyleSheet("border : 1px solid black;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Preview MB 02 (1).PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1131, 80))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 204);\n"
        "border-style: groove;\n"
        "border : 1px solid black;")
        self.widget.setObjectName("widget")
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.toolButton.setStyleSheet("background-color: rgb(255, 255, 204);\n"
        "border: 1px solid black;\n"
        "border-style: groove;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/stock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(50, 40))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        self.toolButton_2.setGeometry(QtCore.QRect(80, 10, 61, 61))
        self.toolButton_2.setStyleSheet("background-color: rgb(255, 255, 204);\n"
        "border: 1px solid black;\n"
        "border-style: groove;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/recipe.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 40))
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.widget)
        self.toolButton_3.setGeometry(QtCore.QRect(150, 10, 61, 61))
        self.toolButton_3.setStyleSheet("background-color: rgb(255, 255, 204);\n"
        "border: 1px solid black;\n"
        "border-style: groove;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(50, 40))
        self.toolButton_3.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        
        self.toolButton_4 = QtWidgets.QToolButton(self.widget)
        self.toolButton_4.setGeometry(QtCore.QRect(220, 10, 61, 61))
        self.toolButton_4.setStyleSheet("background-color: rgb(255, 255, 204);\n"
        "border: 1px solid black;\n"
        "border-style: groove;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/order_iconpng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(50, 40))
        self.toolButton_4.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mehar Baba Resturant - ERP user: " + str(self.username)))
        self.toolButton.setText(_translate("MainWindow", "Stock"))
        self.toolButton_2.setText(_translate("MainWindow", "Recipe"))
        self.toolButton_3.setText(_translate("MainWindow", "Menu"))
        self.toolButton_4.setText(_translate("MainWindow", "Order"))
        
        menu = QtWidgets.QMenu(self.toolButton_3)
        menu_action1 = menu.addAction("Master input")
        menu_action2 = menu.addAction("item")
        menu_action3 = menu.addAction("types of item")
        menu_action4 = menu.addAction("Main Menu")

        menu.setStyleSheet("""
        QMenu {
                background-color: rgb(223, 223, 223);     /* menu background */
                color: black;                             /* text color */
                border: 1px solid gray;
        }
        QMenu::item:selected {                        /* item hover */
                background-color: #a0fff4;
                color: black;
        }
        """)

        order = QtWidgets.QMenu(self.toolButton_4)
        order_action1 = order.addAction("New Order")
        order_action2 = order.addAction("Order Status")
        order_action3 = order.addAction("Order Bill")
        
        order.setStyleSheet("""
        QMenu {
                background-color: rgb(223, 223, 223);     /* menu background */
                color: black;                             /* text color */
                border: 1px solid gray;
        }
        QMenu::item:selected {                        /* item hover */
                background-color: #ffc2aa;
                color: black;
        }
        """)


        self.toolButton_3.setMenu(menu)
        self.toolButton_3.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        menu_action1.triggered.connect(self.menu_option)
        menu_action2.triggered.connect(self.add_item_name_option)
        menu_action3.triggered.connect(self.types_of_item)
        menu_action4.triggered.connect(self.main_menu)

        self.toolButton_4.setMenu(order)
        self.toolButton_4.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        order_action1.triggered.connect(self.new_order)
        order_action2.triggered.connect(self.order_status)
        order_action3.triggered.connect(self.customer_bill)


    #   Menu Frame
    def menu_option(self):
        menu_class(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).menu_frame()

    #   Item Frame    
    def add_item_name_option(self):
        menu_item_class(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).add_item_frame()


    #   Types of item
    def types_of_item(self):
        item_category_class(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).item_category_frame()

    #   Main Menu
    def main_menu(self):
        main_menu_of_item_class(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).main_menu_items_frame()

    #   New Order
    def new_order(self):
        new_order_class(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).new_order_frame()

    #   Punched order status
    def order_status(self):
        punch_order_status(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).punched_order_frame()

    #   Customer Bill
    def customer_bill(self):
        customer_order_bill(self.centralwidget, self.username, self.usertype, self.MainWindow, self.userid).order_bill_fram()