# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from login_backend import login_backend
from homepage import home_screen


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(652, 414)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(652, 414))
        MainWindow.setMaximumSize(QtCore.QSize(652, 414))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Icon MB 02 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 651, 331))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, -20, 651, 341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Preview MB 02 (1).PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 260, 651, 201))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 10, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(301, 31))
        self.lineEdit_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 50, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(301, 31))
        self.lineEdit_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 90, 75, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
        "    background-color: rgb(255, 255, 255);\n"
        "\n"
        "    border: 1px solid #5c5c5c;\n"
        "    border-radius: 5px;\n"
        "    padding: 5px 10px;\n"
        "    color: black;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: qlineargradient(\n"
        "        x1:0, y1:0, x2:0, y2:1,\n"
        "        stop:0 #c0c0c0, stop:1 #909090\n"
        "    );\n"
        "    border-style: solid;\n"
        "}\n"
        "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 90, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
        "    background-color: rgb(255, 255, 255);\n"
        "\n"
        "    border: 1px solid #5c5c5c;\n"
        "    border-radius: 5px;\n"
        "    padding: 5px 10px;\n"
        "    color: black;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: qlineargradient(\n"
        "        x1:0, y1:0, x2:0, y2:1,\n"
        "        stop:0 #c0c0c0, stop:1 #909090\n"
        "    );\n"
        "    border-style: solid;\n"
        "}\n"
        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setDefault(True)
        self.pushButton.setDefault(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mehar Baba Resturant - ERP"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Ok"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.pushButton.clicked.connect(lambda:self.on_click(MainWindow))

    def on_click(self, mainwindow):
        self.username = self.lineEdit_2.text()
        self.password = self.lineEdit_3.text()
        if self.username == "" or self.password == "":
            mainwindow.setEnabled(False)
            self.msg_box = QMessageBox(mainwindow)
            self.msg_box.setWindowTitle('Error')
            self.msg_box.setIcon(QMessageBox.Critical)
            self.msg_box.setText('Username & Password required!')
            self.msg_box.setStandardButtons(QMessageBox.Ok)
            self.msg_box.exec_()
            mainwindow.setEnabled(True)
        else:
            databaseconnection = login_backend(self.username, self.password, mainwindow).check_login_details()
            if databaseconnection == False:
                mainwindow.setEnabled(False)
                self.msg_box = QMessageBox(mainwindow)
                self.msg_box.setWindowTitle('Error')
                self.msg_box.setIcon(QMessageBox.Critical)
                self.msg_box.setText('Connection lost')
                self.msg_box.setStandardButtons(QMessageBox.Ok)
                self.msg_box.exec_()
                mainwindow.setEnabled(True)
            elif databaseconnection == 'Empty':
                mainwindow.setEnabled(False)
                self.msg_box = QMessageBox(mainwindow)
                self.msg_box.setWindowTitle('Error')
                self.msg_box.setIcon(QMessageBox.Critical)
                self.msg_box.setText('user not found')
                self.msg_box.setStandardButtons(QMessageBox.Ok)
                self.msg_box.exec_()
                mainwindow.setEnabled(True)
            elif databaseconnection == 'deactive':
                mainwindow.setEnabled(False)
                self.msg_box = QMessageBox(mainwindow)
                self.msg_box.setWindowTitle('Error')
                self.msg_box.setIcon(QMessageBox.Critical)
                self.msg_box.setText('Contact admin, user is deactivate')
                self.msg_box.setStandardButtons(QMessageBox.Ok)
                self.msg_box.exec_()
                mainwindow.setEnabled(True)
            elif databaseconnection != []:
                usertype = databaseconnection[0]
                userid = databaseconnection[1]
                if usertype == "001":
                    mainwindow.close()  #   fully close login window
                    self.homepage_window = QtWidgets.QMainWindow()
                    self.homepage_ui = home_screen()
                    self.homepage_ui.setupUi(self.homepage_window,self.username, usertype, userid)
                    self.homepage_window.show()

    def enable_main_window(self, mainwindow):
        mainwindow.setEnabled(True)

    #   Enter
    def keyPressEvent(self, event):
        if event.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
            focus_widget = self.focusWidget()
            if isinstance(focus_widget, QtWidgets.QPushButton):
                focus_widget.click() 




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
